Acme\DemoBundle\Entity\Library:
    type: entity
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToMany:
        medias:
            targetEntity: Media
            cascade:
                - persist